#!/usr/bin/env node
// Writes the current package's version into a source file before its build,
// so the version a package reports (or bundles into games) always matches
// its package.json. Run from the package directory:
//   node ../../scripts/write-version.mjs src/version.ts

import fs from 'node:fs';
import path from 'node:path';

const [outputPath] = process.argv.slice(2);
if (!outputPath) {
  throw new Error('Usage: write-version.mjs <output file>');
}

const packageDir = process.cwd();
const { version } = JSON.parse(fs.readFileSync(path.join(packageDir, 'package.json'), 'utf8'));

fs.writeFileSync(
  path.join(packageDir, outputPath),
  `// Generated by scripts/write-version.mjs from package.json. Don't edit.\nexport const SDK_VERSION = '${version}';\n`,
  'utf8'
);
